name: E2E on Chrome

on: [push]

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install dependencies
              run: |
                  cd ./exactly-challenge
                  npm ci

            - name: Cypress run
              uses: cypress-io/github-action@v3
              with:
                  working-directory: exactly-challenge
                  browser: chrome
                  build: npm run build
                  start: npm run start
                  wait-on: "http://localhost:3000"
